- src: galaxyproject.galaxy
  version: 0.9.11
- src: galaxyproject.nginx
  version: 0.6.4
- src: galaxyproject.postgresql
  version: 1.0.3
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 2.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.4
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: cyverse-ansible.singularity
  version: 048c4f178077d05c1e67ae8d9893809aac9ab3b7
- src: gantsign.golang
  version: 2.6.3
- src: galaxyproject.cvmfs
  version: 0.2.13
- src: dj-wasabi.telegraf
  version: 0.13.0
- src: influxdata.chrony
  version: master
- src: usegalaxy_eu.gxadmin
  version: 0.0.3
